In [61]:
def make_qft(qubits):
    """Generator for the QFT on a list of qubits."""
    qreg = list(qubits)
    while len(qreg) > 0:
        q_head = qreg.pop(0)
        yield cirq.H(q_head)
        for i, qubit in enumerate(qreg):
            yield (cirq.CZ ** (1 / 2 ** (i + 1)))(qubit, q_head)

qubits = cirq.LineQubit.range(4)
qft= cirq.Circuit(make_qft(qubits))
print(qft)

                  ┌───────┐   ┌────────────┐   ┌───────┐
0: ───H───@────────@───────────@───────────────────────────────────────
          │        │           │
1: ───────@^0.5────┼─────H─────┼──────@─────────@──────────────────────
                   │           │      │         │
2: ────────────────@^0.25──────┼──────@^0.5─────┼─────H────@───────────
                               │                │          │
3: ────────────────────────────@^(1/8)──────────@^0.25─────@^0.5───H───
                  └───────┘   └────────────┘   └───────┘


In [4]:
def make_qft_Inverse(qubits):
    qreg = list(qubits)[::-1]
    while len(qreg) > 0:
        q_head = qreg.pop(0)
        yield cirq.H(q_head)
        for i, qubit in enumerate(qreg):
            yield (cirq.CZ ** (-1 / 2 ** (i + 1)))(qubit, q_head)

qubits = cirq.LineQubit.range(4)
iqft = cirq.Circuit(make_qft_Inverse(qubits))
print(iqft)


                   ┌────────┐   ┌──────────────┐   ┌────────┐
0: ──────────────────────────────@──────────────────@───────────@────────H───
                                 │                  │           │
1: ─────────────────@────────────┼───────@──────────┼──────H────@^-0.5───────
                    │            │       │          │
2: ───────@─────────┼──────H─────┼───────@^-0.5─────@^-0.25──────────────────
          │         │            │
3: ───H───@^-0.5────@^-0.25──────@^(-1/8)────────────────────────────────────
                   └────────┘   └──────────────┘   └────────┘


In [50]:
import pandas as pd
import tensorflow as tf
import cirq
import numpy as np


def ResizeTo16x16(x_train, x_test):
    # Thêm chiều kênh (channel) để phù hợp với định dạng ảnh
    x_train = tf.expand_dims(x_train, axis=-1)  # Từ (batch_size, 28, 28) -> (batch_size, 28, 28, 1)
    x_test = tf.expand_dims(x_test, axis=-1)  # Từ (batch_size, 28, 28) -> (batch_size, 28, 28, 1)

    
    # Resize từ 28x28 xuống 16x16
    x_test = tf.image.resize(x_test, [16, 16], method='bilinear')
    x_train = tf.image.resize(x_train, [16, 16], method='bilinear')
    x_train = tf.squeeze(x_train, axis=-1)  # Loại bỏ chiều kênh (kênh ảnh)
    x_test = tf.squeeze(x_test, axis=-1)    # Loại bỏ chiều kênh (kênh ảnh)

    
    return x_test, x_train
# Tải dữ liệu MNIST
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
#x_train, x_test = ResizeTo16x16(x_train, x_test)
# Số lượng mẫu bạn muốn giảm xuống
num_train_samples = 1000  # Giảm xuống 10.000 mẫu
num_test_samples = 200  # Giảm xuống 2.000 mẫu

# Giảm số lượng mẫu huấn luyện và kiểm tra bằng cách chọn ngẫu nhiên
x_train_reduced = x_train[:num_train_samples]  # Lấy số lượng mẫu đầu tiên
y_train_reduced = y_train[:num_train_samples]  # Lấy nhãn tương ứng

x_test_reduced = x_test[:num_test_samples]  # Lấy số lượng mẫu đầu tiên
y_test_reduced = y_test[:num_test_samples]  # Lấy nhãn tương ứng

# Kiểm tra lại hình dạng của dữ liệu đã giảm
print("x_train_reduced shape:", x_train_reduced.shape)
print("y_train_reduced shape:", y_train_reduced.shape)
print("x_test_reduced shape:", x_test_reduced.shape)
print("y_test_reduced shape:", y_test_reduced.shape)
x_train=x_train_reduced
y_train=y_train_reduced
x_test=x_test_reduced
y_test=y_test_reduced
print(x_test)


x_train_reduced shape: (1000, 28, 28)
y_train_reduced shape: (1000,)
x_test_reduced shape: (200, 28, 28)
y_test_reduced shape: (200,)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [63]:
import pandas as pd
import tensorflow as tf
import cirq
import numpy as np

def LoadData(file_path):            
    data = pd.read_csv(file_path)
    y_data = data.iloc[:, 0].values
    x_data = data.iloc[:, 1:].values
    x_data = tf.convert_to_tensor(x_data, dtype=tf.float32)
    y_data = tf.convert_to_tensor(y_data, dtype=tf.int32)
    return x_data, y_data

def SplitData(x_data, y_data, train_percent_size):
    train_size = int(len(x_data) * train_percent_size)
    x_train = x_data[:train_size]
    y_train = y_data[:train_size]
    x_test = x_data[train_size:]
    y_test = y_data[train_size:]
    return x_train, y_train, x_test, y_test

def PrintInfo(x_train, y_train, x_test, y_test):
    print(f"x_train shape: {x_train.shape}")
    print(f"y_train shape: {y_train.shape}")
    print(f"x_test shape: {x_test.shape}")
    print(f"y_test shape: {y_test.shape}")

def pad_to_power_of_two(arr):
    """
    Pad the array to the nearest power of 2 length.
    """
    target_length = 2**int(np.ceil(np.log2(len(arr))))
    return np.pad(arr, (0, target_length - len(arr)), 'constant')

def amplitude_embedding(x_train, qubits):
    """
    Encode classical data into quantum states using amplitude embedding.
    Args:
        x_train: Classical data to be encoded.
        qubits: List of qubits to encode the data.
    """
    circuit = cirq.Circuit()
    for sample in x_train:
        # Normalize the sample to create a valid quantum state
        sample = pad_to_power_of_two(sample)
        norm = np.linalg.norm(sample)
        normalized_sample = sample / norm if norm != 0 else sample
        circuit.append(cirq.StatePreparationChannel(normalized_sample)(*qubits))
    return circuit

def qubits_data(x_train):
    # Assuming the number of qubits needed is the same as the length of each sample
    num_qubits = int(np.ceil(np.log2(len(x_train[0]))))
    return [cirq.GridQubit(0, i) for i in range(num_qubits)]

def n_qubits(x_train):
    return int(np.ceil(np.log2(len(x_train[0]))))




x_data, y_data = LoadData("mnist.csv")

x_train, y_train, x_test, y_test = SplitData(x_data, y_data, 0.8)

PrintInfo(x_train, y_train, x_test, y_test)


#x_train = np.array([[1, 2, 3]])        # Example usage
qubits = qubits_data(x_train)
amplitude_embedding_circuit = amplitude_embedding(x_train, qubits)
print(amplitude_embedding_circuit)

#simulator = cirq.Simulator()
#result = simulator.simulate(amplitude_embedding_circuit)

# Print the final state vector
#print("\nFinal State Vector:")
#print(result.final_state_vector)

# Print the probability distribution
#probabilities = np.abs(result.final_state_vector) ** 2
#for i, prob in enumerate(probabilities):
#    print(f"State |{i:0{len(qubits)}b}>: Probability = {prob:.4f}")     

x_train shape: (159, 784)
y_train shape: (159,)
x_test shape: (40, 784)
y_test shape: (40,)
(0, 0): ───StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────

In [59]:
import pandas as pd
import tensorflow as tf
import cirq
import numpy as np

# Kiểm tra lại hình dạng của dữ liệu đã giảm
print("x_train_reduced shape:", x_train_reduced.shape)
print("y_train_reduced shape:", y_train_reduced.shape)
print("x_test_reduced shape:", x_test_reduced.shape)
print("y_test_reduced shape:", y_test_reduced.shape)
x_train=x_train_reduced
y_train=y_train_reduced
x_test=x_test_reduced
y_test=y_test_reduced

def pad_to_power_of_two(arr):
    """
    Pad the array to the nearest power of 2 length.
    """
    target_length = 2**int(np.ceil(np.log2(len(arr))))
    return np.pad(arr, (0, target_length - len(arr)), 'constant')

def amplitude_embedding(x_train, qubits):
    """
    Encode classical data into quantum states using amplitude embedding.
    Args:
        x_train: Classical data to be encoded.
        qubits: List of qubits to encode the data.
    """
    circuit = cirq.Circuit()
    for sample in x_train:
        # Làm phẳng sample thành mảng 1D
        sample = sample.flatten()  # Flatten the 2D array to 1D
        sample = pad_to_power_of_two(sample)  # Thêm padding nếu cần
        norm = np.linalg.norm(sample)
        normalized_sample = sample / norm if norm != 0 else sample
        # Thêm vào mạch lượng tử
        circuit.append(cirq.StatePreparationChannel(normalized_sample)(*qubits))
    return circuit

def qubits_data(x_train):
    # Giả sử số qubit cần thiết là log2 của chiều dài mỗi mẫu
    num_qubits = int(np.ceil(np.log2(len(x_train[0].flatten()))))  # Lấy chiều dài 1D của mẫu
    return [cirq.GridQubit(0, i) for i in range(num_qubits)]

def n_qubits(x_train):
    return int(np.ceil(np.log2(len(x_train[0].flatten()))))  # Sử dụng chiều dài 1D

# Quá trình nhúng dữ liệu vào qubit
qubits = qubits_data(x_train)
amplitude_embedding_circuit = amplitude_embedding(x_train, qubits)
print(amplitude_embedding_circuit)
print(n_qubits(x_train))

# Bước tiếp theo là mô phỏng hoặc kiểm tra mạch
# simulator = cirq.Simulator()
# result = simulator.simulate(amplitude_embedding_circuit)

# In ra mạch đã tạo
# print("\nFinal State Vector:")
# print(result.final_state_vector)

# In ra phân phối xác suất
# probabilities = np.abs(result.final_state_vector) ** 2
# for i, prob in enumerate(probabilities):
#     print(f"State |{i:0{len(qubits)}b}>: Probability = {prob:.4f}")


x_train_reduced shape: (1000, 28, 28)
y_train_reduced shape: (1000,)
x_test_reduced shape: (200, 28, 28)
y_test_reduced shape: (200,)
(0, 0): ───StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────Stat

In [103]:

def qft(qubits):
    """Quantum Fourier Transform on the given list of qubits."""
    circuit = cirq.Circuit()
    
    n = len(qubits)
    for i in range(n):
        circuit.append(cirq.H(qubits[i]))
        for j in range(i + 1, n):
            angle = np.pi / (2 ** (j - i))
            circuit.append(cirq.CZ(qubits[j], qubits[i]) ** (angle / np.pi))
    return circuit


def inverse_qft(qubits):
    circuit = cirq.Circuit()
    n = len(qubits)
    for i in reversed(range(n)):
        for j in reversed(range(i + 1, n)):
            angle = -np.pi / (2 ** (j - i))
            circuit.append(cirq.CZ(qubits[j], qubits[i]) ** (angle / np.pi))
        circuit.append(cirq.H(qubits[i]))
    return circuit


def prepare_input_state(qubits):
    """
    Prepare a custom input state for the input qubits.
    Args:
        qubits: List of qubits to prepare the input state.
    """
    circuit = cirq.Circuit()
    for i, qubit in enumerate(qubits):
        if i % 2 == 0:  # Example: Apply X gate to even-indexed qubits
            circuit.append(cirq.X(qubit))
    return circuit


def prepare_trainable_kernel(qubits, params):
    """
    Prepare a trainable quantum kernel on the given qubits using parameterized rotations.
    Args:
        qubits: List of qubits for the kernel.
        params: List of parameters to control the rotations.
    """
    circuit = cirq.Circuit()
    for q, param in zip(qubits, params):
        circuit.append(cirq.ry(param)(q))
    return circuit


def mapping_m(input_qubits, kernel_qubits, params):
    circuit = cirq.Circuit()
    for i_q, k_q, param in zip(input_qubits, kernel_qubits, params):
        # Replace CZ with parameterized controlled-RY gates
        circuit.append(cirq.ry(param).controlled()(i_q, k_q))
    return circuit


def quantum_fourier_convolution_layer(input_qubits, kernel_qubits, params):

    circuit = cirq.Circuit()
    
    # Apply QFT to input and kernel
    circuit += qft(input_qubits)
    circuit += qft(kernel_qubits)

    # Mapping M() - Elementwise multiplication in the frequency domain
    circuit += mapping_m(input_qubits, kernel_qubits, params)

    # Apply iQFT to input and kernel
    circuit += inverse_qft(input_qubits)
    circuit += inverse_qft(kernel_qubits)

    return circuit


def main():
    """Simulate the Quantum Fourier Convolutional Layer."""
    n = 13  # Number of qubits per register

    # Create input and kernel qubits
    input_qubits = [cirq.LineQubit(i) for i in range(n)]
    kernel_qubits = [cirq.LineQubit(i + n) for i in range(n)]

    # Trainable kernel parameters
    kernel_params = [0.1, 0.3, 0.5]  # Example parameters

    # Prepare circuits
    prep_circuit = cirq.Circuit()
    prep_circuit += prepare_input_state(input_qubits)  # Prepare a custom input state
    prep_circuit += prepare_trainable_kernel(kernel_qubits, kernel_params)

    # Build the QFT-based convolution layer
    qfc_layer = quantum_fourier_convolution_layer(input_qubits, kernel_qubits, kernel_params)

    # Add measurement
    measurement_circuit = cirq.Circuit()
    measurement_circuit.append(cirq.measure(*input_qubits, *kernel_qubits, key="result"))

    # Combine all circuits
    full_circuit = prep_circuit + qfc_layer + measurement_circuit

    print("Full Quantum Fourier Convolutional Circuit:")
    print(full_circuit)

    # Simulate the circuit
    simulator = cirq.Simulator()

    # Simulate state vector
    result = simulator.simulate(full_circuit)
    print("\nFinal state vector:")
    print(result.final_state_vector)

    # Simulate measurements
    repetitions = 1000
    measurement_result = simulator.run(full_circuit, repetitions=repetitions)
    print("\nMeasurement results (histogram):")
    print(measurement_result.histogram(key="result"))


if __name__ == "__main__":
    main()


Full Quantum Fourier Convolutional Circuit:
                                    ┌───────┐   ┌────────────┐   ┌───────────────┐   ┌───────────────────┐   ┌──────────────────────┐   ┌──────────────────────────┐   ┌─────────────────────────────┐   ┌─────────────────────────────────┐   ┌────────────────────────────────────┐   ┌────────────────────────────────────┐   ┌───────────────────────────────────────┐   ┌────────────────────────────────────┐   ┌────────────────────────────────────┐   ┌─────────────────────────────────┐   ┌─────────────────────────────┐   ┌──────────────────────────┐   ┌──────────────────────┐   ┌───────────────────┐   ┌───────────────┐   ┌────────────┐   ┌───────┐                           ┌───────┐   ┌────────────┐   ┌───────────────┐   ┌───────────────────┐   ┌──────────────────────┐   ┌──────────────────────────┐   ┌─────────────────────────────┐   ┌─────────────────────────────────┐   ┌────────────────────────────────────┐   ┌────────────────────────────────────┐

MemoryError: Unable to allocate 512. MiB for an array with shape (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2) and data type complex64

In [60]:
import pandas as pd
import tensorflow as tf
import cirq
import numpy as np

def LoadData(file_path):            
    data = pd.read_csv(file_path)
    y_data = data.iloc[:, 0].values
    x_data = data.iloc[:, 1:].values
    x_data = tf.convert_to_tensor(x_data, dtype=tf.float32)
    y_data = tf.convert_to_tensor(y_data, dtype=tf.int32)
    return x_data, y_data

def SplitData(x_data, y_data, train_percent_size):
    train_size = int(len(x_data) * train_percent_size)
    x_train = x_data[:train_size]
    y_train = y_data[:train_size]
    x_test = x_data[train_size:]
    y_test = y_data[train_size:]
    return x_train, y_train, x_test, y_test

def PrintInfo(x_train, y_train, x_test, y_test):
    print(f"x_train shape: {x_train.shape}")
    print(f"y_train shape: {y_train.shape}")
    print(f"x_test shape: {x_test.shape}")
    print(f"y_test shape: {y_test.shape}")

def pad_to_power_of_two(arr):
    """
    Pad the array to the nearest power of 2 length.
    """
    target_length = 2**int(np.ceil(np.log2(len(arr))))
    return np.pad(arr, (0, target_length - len(arr)), 'constant')

def amplitude_embedding(x_train, qubits):
    """
    Encode classical data into quantum states using amplitude embedding.
    Args:
        x_train: Classical data to be encoded.
        qubits: List of qubits to encode the data.
    """
    circuit = cirq.Circuit()
    for sample in x_train:
        # Normalize the sample to create a valid quantum state
        sample = pad_to_power_of_two(sample)
        norm = np.linalg.norm(sample)
        normalized_sample = sample / norm if norm != 0 else sample
        circuit.append(cirq.StatePreparationChannel(normalized_sample)(*qubits))
    return circuit

def qubits_data(x_train):
    # Assuming the number of qubits needed is the same as the length of each sample
    num_qubits = int(np.ceil(np.log2(len(x_train[0]))))
    return [cirq.GridQubit(0, i) for i in range(num_qubits)]

def n_qubits(x_train):
    return int(np.ceil(np.log2(len(x_train[0]))))




x_data, y_data = LoadData("mnist.csv")

x_train, y_train, x_test, y_test = SplitData(x_data, y_data, 0.8)

PrintInfo(x_train, y_train, x_test, y_test)


#x_train = np.array([[1, 2, 3]])        # Example usage
qubits = qubits_data(x_train)
amplitude_embedding_circuit = amplitude_embedding(x_train, qubits)
print(amplitude_embedding_circuit)
print(n_qubits(x_train))

#simulator = cirq.Simulator()
#result = simulator.simulate(amplitude_embedding_circuit)

# Print the final state vector
#print("\nFinal State Vector:")
#print(result.final_state_vector)

# Print the probability distribution
#probabilities = np.abs(result.final_state_vector) ** 2
#for i, prob in enumerate(probabilities):
#    print(f"State |{i:0{len(qubits)}b}>: Probability = {prob:.4f}")     

x_train shape: (159, 784)
y_train shape: (159,)
x_test shape: (40, 784)
y_test shape: (40,)
(0, 0): ───StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────StatePreparation[1]────